CREATE TABLE IF NOT EXISTS "country" (
  "country_code" CHAR PRIMARY KEY,
  "country" CHAR
);

CREATE TABLE IF NOT EXISTS "city" (
  "city_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_name" CHAR,
  "country_code" CHAR
);

CREATE TABLE IF NOT EXISTS "industry_tags" (
  "industry_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "industry_tag" CHAR
);

CREATE TABLE IF NOT EXISTS "status" (
  "status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_active" BOOLEAN,
  "status" CHAR
);

CREATE TABLE IF NOT EXISTS "company" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" CHAR,
  "funding_amount" DECIMAL,
  "start_year" INT,
  "website" CHAR,
  "city_id" INT,
  "status_id" INT
);

CREATE TABLE IF NOT EXISTS "company_industries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" INT,
  "industry_id" INT
);

CREATE TABLE IF NOT EXISTS "country_investments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_code" VARCHAR(10),
  "business_stage" VARCHAR(100),
  "year" INT,
  "amount" DECIMAL
);

ALTER TABLE "country_investments" 
  ADD FOREIGN KEY ("country_code") REFERENCES "country" ("country_code");

ALTER TABLE "city" 
  ADD FOREIGN KEY ("country_code") REFERENCES "country" ("country_code");

ALTER TABLE "company" 
  ADD FOREIGN KEY ("city_id") REFERENCES "city" ("city_id");

ALTER TABLE "company" 
  ADD FOREIGN KEY ("status_id") REFERENCES "status" ("status_id");

ALTER TABLE "company_industries" 
  ADD FOREIGN KEY ("company_id") REFERENCES "company" ("id");

ALTER TABLE "company_industries" 
  ADD FOREIGN KEY ("industry_id") REFERENCES "industry_tags" ("industry_id");


------------------------------------------------------------------------------------------------------------------------------------------------
/* Fixing the datatype of tables where CHAR type is used. CHAR assumes CHAR(1) by default so I am modifying the datatypes appropriately below.*/

ALTER TABLE "country"
  ALTER COLUMN country_code TYPE VARCHAR(10),
  ALTER COLUMN country TYPE VARCHAR(50);

ALTER TABLE "city"
  ALTER COLUMN "city_name" TYPE VARCHAR(500),
  ALTER COLUMN "country_code" TYPE VARCHAR(10);

ALTER TABLE "industry_tags" 
  ALTER COLUMN "industry_tag" TYPE VARCHAR(250);


ALTER TABLE "status" 
  ALTER column "status" TYPE VARCHAR(10);


ALTER TABLE "company"
  ALTER COLUMN "company_name" TYPE VARCHAR(5000),
  ALTER COLUMN "website" TYPE VARCHAR(5000);


